# Generated by Django 5.2.1 on 2025-05-22 23:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EasyInsurance', '0002_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='insurance',
            name='user',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='insurances', to='EasyInsurance.user'),
        ),
    ]
