# Generated by Django 5.2.1 on 2025-05-22 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EasyInsurance', '0003_insurance_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insurance',
            name='insurance_id',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='insurance',
            unique_together={('user', 'insurance_id')},
        ),
    ]
